# Generated by Django 3.2.8 on 2021-11-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211110_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='aboutMe',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='о себе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tagline',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='теги'),
        ),
    ]
